### ISSUE TITLE
Most times application show some connecting error messages even after database ever is being ON

### ISSUE THREAD

**Issue by Kushan2k** [Kushan2k/FoodsFly-a-food-ordering-system#1]
application crashes if it cloud not connect to the database system according to the connection defined in the conn.php file

**Comment by heshara2000** [comment]
The db server itself may be offline or experiencing issues

**Comment by InulaC** [comment]
It occurs due to database not being connected maybe? Or an error in the hosting server

**Comment by Kalindu00** [comment]
Error causes
Make Sure  Domain Is Pointing to Host Provider. Check  Database Server. Check the Database Login Credentials.

**Comment by harshani2000** [comment]
Make user to turn on the mysql server before opening the web application.And also check the connection details like username ,host or the password.Sometimes connection port is important too.
